# coding: utf-8

"""
    CESv2 Remail Network API

    CESv2 Remail Network API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: cie-eng.network-hps-team@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.virtualservice_api import VirtualserviceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVirtualserviceApi(unittest.TestCase):
    """VirtualserviceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.virtualservice_api.VirtualserviceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_virtual_service(self):
        """Test case for add_virtual_service

        Provision a new virtualservice to a specific site  # noqa: E501
        """
        pass

    def test_delete_virtual_service(self):
        """Test case for delete_virtual_service

        Delete an existing virtualservice by id  # noqa: E501
        """
        pass

    def test_get_virtual_service(self):
        """Test case for get_virtual_service

        Get a new virtualservice by id  # noqa: E501
        """
        pass

    def test_modify_virtual_service(self):
        """Test case for modify_virtual_service

        Modify an existing virtualservice by id  # noqa: E501
        """
        pass

    def test_virtualservice_get(self):
        """Test case for virtualservice_get

        List all virtualservices in site  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
