# coding: utf-8

"""
    CESv2 Remail Network API

    CESv2 Remail Network API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: cie-eng.network-hps-team@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.vs_not_found_error_response import VSNotFoundErrorResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestVSNotFoundErrorResponse(unittest.TestCase):
    """VSNotFoundErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVSNotFoundErrorResponse(self):
        """Test VSNotFoundErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vs_not_found_error_response.VSNotFoundErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
