# coding: utf-8

"""
    CESv2 Remail Network API

    CESv2 Remail Network API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: cie-eng.network-hps-team@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.jwt_authorization_error_response import JWTAuthorizationErrorResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestJWTAuthorizationErrorResponse(unittest.TestCase):
    """JWTAuthorizationErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJWTAuthorizationErrorResponse(self):
        """Test JWTAuthorizationErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.jwt_authorization_error_response.JWTAuthorizationErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
