# coding: utf-8

"""
    CESv2 Remail Network API

    CESv2 Remail Network API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: cie-eng.network-hps-team@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.segment_api import SegmentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSegmentApi(unittest.TestCase):
    """SegmentApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.segment_api.SegmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_next_segment(self):
        """Test case for get_next_segment

        gets next Segment  # noqa: E501
        """
        pass

    def test_get_segments(self):
        """Test case for get_segments

        Finds supported segments  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
