# coding: utf-8

"""
    CESv2 Remail Network API

    CESv2 Remail Network API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: cie-eng.network-hps-team@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class VirtualserviceApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_virtual_service(self, **kwargs):  # noqa: E501
        """Provision a new virtualservice to a specific site  # noqa: E501

        Provision ESA virtual service on a specific site. IPv4 address will be auto picked from IPAM  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_virtual_service(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param VirtualServiceRequest virtualservice: The virtual service to be created
        :param str authorization: A signed and valid Streamline IAM access token
        :return: VirtualService
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_virtual_service_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.add_virtual_service_with_http_info(**kwargs)  # noqa: E501
            return data

    def add_virtual_service_with_http_info(self, **kwargs):  # noqa: E501
        """Provision a new virtualservice to a specific site  # noqa: E501

        Provision ESA virtual service on a specific site. IPv4 address will be auto picked from IPAM  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_virtual_service_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param VirtualServiceRequest virtualservice: The virtual service to be created
        :param str authorization: A signed and valid Streamline IAM access token
        :return: VirtualService
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['virtualservice', 'authorization']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_virtual_service" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'virtualservice' in params:
            body_params = params['virtualservice']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtTokenValidate']  # noqa: E501

        return self.api_client.call_api(
            '/virtualservice', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='VirtualService',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_virtual_service(self, id, **kwargs):  # noqa: E501
        """Delete an existing virtualservice by id  # noqa: E501

        Deletes ESA virtual service on a specific site by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_virtual_service(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: The virtual service id that needs to be deleted (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_virtual_service_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_virtual_service_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def delete_virtual_service_with_http_info(self, id, **kwargs):  # noqa: E501
        """Delete an existing virtualservice by id  # noqa: E501

        Deletes ESA virtual service on a specific site by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_virtual_service_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: The virtual service id that needs to be deleted (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_virtual_service" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `delete_virtual_service`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtTokenValidate']  # noqa: E501

        return self.api_client.call_api(
            '/virtualservice/{id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_virtual_service(self, id, **kwargs):  # noqa: E501
        """Get a new virtualservice by id  # noqa: E501

        Get a new virtualservice by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_virtual_service(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: The virtual service id that needs to be fetched (required)
        :param str name: Customer name
        :param str site_id: Site id for filter
        :return: VirtualService
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_virtual_service_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_virtual_service_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def get_virtual_service_with_http_info(self, id, **kwargs):  # noqa: E501
        """Get a new virtualservice by id  # noqa: E501

        Get a new virtualservice by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_virtual_service_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: The virtual service id that needs to be fetched (required)
        :param str name: Customer name
        :param str site_id: Site id for filter
        :return: VirtualService
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'name', 'site_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_virtual_service" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `get_virtual_service`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'name' in params:
            query_params.append(('name', params['name']))  # noqa: E501
        if 'site_id' in params:
            query_params.append(('site_id', params['site_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtTokenValidate']  # noqa: E501

        return self.api_client.call_api(
            '/virtualservice/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='VirtualService',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def modify_virtual_service(self, id, **kwargs):  # noqa: E501
        """Modify an existing virtualservice by id  # noqa: E501

        Modifies ESA virtual service on a speciic site by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.modify_virtual_service(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: The virtual service id that needs to be modified (required)
        :param VirtualServiceModifyRequest virtualservice: The virtual service to be modified
        :return: VirtualService
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.modify_virtual_service_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.modify_virtual_service_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def modify_virtual_service_with_http_info(self, id, **kwargs):  # noqa: E501
        """Modify an existing virtualservice by id  # noqa: E501

        Modifies ESA virtual service on a speciic site by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.modify_virtual_service_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: The virtual service id that needs to be modified (required)
        :param VirtualServiceModifyRequest virtualservice: The virtual service to be modified
        :return: VirtualService
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'virtualservice']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method modify_virtual_service" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `modify_virtual_service`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'virtualservice' in params:
            body_params = params['virtualservice']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtTokenValidate']  # noqa: E501

        return self.api_client.call_api(
            '/virtualservice/{id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='VirtualService',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def virtualservice_get(self, **kwargs):  # noqa: E501
        """List all virtualservices in site  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.virtualservice_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: A signed and valid Streamline IAM access token
        :param str site: Filtering all sites by sites
        :return: list[VirtualService]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.virtualservice_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.virtualservice_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def virtualservice_get_with_http_info(self, **kwargs):  # noqa: E501
        """List all virtualservices in site  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.virtualservice_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: A signed and valid Streamline IAM access token
        :param str site: Filtering all sites by sites
        :return: list[VirtualService]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['authorization', 'site']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method virtualservice_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'site' in params:
            query_params.append(('Site', params['site']))  # noqa: E501

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtTokenValidate']  # noqa: E501

        return self.api_client.call_api(
            '/virtualservice', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[VirtualService]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
