# coding: utf-8

# flake8: noqa
"""
    CESv2 Remail Network API

    CESv2 Remail Network API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: cie-eng.network-hps-team@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.create_vs_invalid_input_error_response import CreateVSInvalidInputErrorResponse
from swagger_client.models.create_vs_no_free_ip import CreateVSNoFreeIP
from swagger_client.models.forbidden import Forbidden
from swagger_client.models.general_internal_error_response import GeneralInternalErrorResponse
from swagger_client.models.host import Host
from swagger_client.models.host_ip import HostIp
from swagger_client.models.invalid_site_id import InvalidSiteID
from swagger_client.models.ip_address import IpAddress
from swagger_client.models.jwt_authorization_error_response import JWTAuthorizationErrorResponse
from swagger_client.models.load_balancer import LoadBalancer
from swagger_client.models.nat import Nat
from swagger_client.models.segment import Segment
from swagger_client.models.site import Site
from swagger_client.models.site_not_found_error_response import SiteNotFoundErrorResponse
from swagger_client.models.site_request import SiteRequest
from swagger_client.models.subnet import Subnet
from swagger_client.models.vs_modify_conflict import VSModifyConflict
from swagger_client.models.vs_modify_invalid_input import VSModifyInvalidInput
from swagger_client.models.vs_not_found_error_response import VSNotFoundErrorResponse
from swagger_client.models.vip import Vip
from swagger_client.models.virtual_service import VirtualService
from swagger_client.models.virtual_service_modify_request import VirtualServiceModifyRequest
from swagger_client.models.virtual_service_request import VirtualServiceRequest
from swagger_client.models.virtual_service_server_pool import VirtualServiceServerPool
