# coding: utf-8

"""
    CESv2 Remail Network API

    CESv2 Remail Network API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: cie-eng.network-hps-team@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.host_ip import HostIp  # noqa: F401,E501


class Host(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ip': 'HostIp',
        'enabled': 'bool'
    }

    attribute_map = {
        'ip': 'ip',
        'enabled': 'enabled'
    }

    def __init__(self, ip=None, enabled=None):  # noqa: E501
        """Host - a model defined in Swagger"""  # noqa: E501

        self._ip = None
        self._enabled = None
        self.discriminator = None

        if ip is not None:
            self.ip = ip
        if enabled is not None:
            self.enabled = enabled

    @property
    def ip(self):
        """Gets the ip of this Host.  # noqa: E501


        :return: The ip of this Host.  # noqa: E501
        :rtype: HostIp
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this Host.


        :param ip: The ip of this Host.  # noqa: E501
        :type: HostIp
        """

        self._ip = ip

    @property
    def enabled(self):
        """Gets the enabled of this Host.  # noqa: E501


        :return: The enabled of this Host.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this Host.


        :param enabled: The enabled of this Host.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Host, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Host):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
