# coding: utf-8

"""
    CESv2 Remail Network API

    CESv2 Remail Network API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: cie-eng.network-hps-team@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Subnet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'subnet_id': 'str',
        'mask_bits': 'int'
    }

    attribute_map = {
        'type': 'type',
        'subnet_id': 'subnet_id',
        'mask_bits': 'mask_bits'
    }

    def __init__(self, type=None, subnet_id=None, mask_bits=None):  # noqa: E501
        """Subnet - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._subnet_id = None
        self._mask_bits = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if subnet_id is not None:
            self.subnet_id = subnet_id
        if mask_bits is not None:
            self.mask_bits = mask_bits

    @property
    def type(self):
        """Gets the type of this Subnet.  # noqa: E501


        :return: The type of this Subnet.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Subnet.


        :param type: The type of this Subnet.  # noqa: E501
        :type: str
        """
        if type is not None and not re.search(r'^V(4|6)$', type):  # noqa: E501
            raise ValueError(r"Invalid value for `type`, must be a follow pattern or equal to `/^V(4|6)$/`")  # noqa: E501

        self._type = type

    @property
    def subnet_id(self):
        """Gets the subnet_id of this Subnet.  # noqa: E501


        :return: The subnet_id of this Subnet.  # noqa: E501
        :rtype: str
        """
        return self._subnet_id

    @subnet_id.setter
    def subnet_id(self, subnet_id):
        """Sets the subnet_id of this Subnet.


        :param subnet_id: The subnet_id of this Subnet.  # noqa: E501
        :type: str
        """
        if subnet_id is not None and not re.search(r'^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$', subnet_id):  # noqa: E501
            raise ValueError(r"Invalid value for `subnet_id`, must be a follow pattern or equal to `/^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$/`")  # noqa: E501

        self._subnet_id = subnet_id

    @property
    def mask_bits(self):
        """Gets the mask_bits of this Subnet.  # noqa: E501


        :return: The mask_bits of this Subnet.  # noqa: E501
        :rtype: int
        """
        return self._mask_bits

    @mask_bits.setter
    def mask_bits(self, mask_bits):
        """Sets the mask_bits of this Subnet.


        :param mask_bits: The mask_bits of this Subnet.  # noqa: E501
        :type: int
        """

        self._mask_bits = mask_bits

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Subnet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Subnet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
