# coding: utf-8

"""
    CESv2 Remail Network API

    CESv2 Remail Network API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: cie-eng.network-hps-team@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.host import Host  # noqa: F401,E501
from swagger_client.models.load_balancer import LoadBalancer  # noqa: F401,E501


class VirtualServiceServerPool(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lb_algorithm': 'LoadBalancer',
        'servers': 'list[Host]'
    }

    attribute_map = {
        'lb_algorithm': 'lb_algorithm',
        'servers': 'servers'
    }

    def __init__(self, lb_algorithm=None, servers=None):  # noqa: E501
        """VirtualServiceServerPool - a model defined in Swagger"""  # noqa: E501

        self._lb_algorithm = None
        self._servers = None
        self.discriminator = None

        if lb_algorithm is not None:
            self.lb_algorithm = lb_algorithm
        if servers is not None:
            self.servers = servers

    @property
    def lb_algorithm(self):
        """Gets the lb_algorithm of this VirtualServiceServerPool.  # noqa: E501


        :return: The lb_algorithm of this VirtualServiceServerPool.  # noqa: E501
        :rtype: LoadBalancer
        """
        return self._lb_algorithm

    @lb_algorithm.setter
    def lb_algorithm(self, lb_algorithm):
        """Sets the lb_algorithm of this VirtualServiceServerPool.


        :param lb_algorithm: The lb_algorithm of this VirtualServiceServerPool.  # noqa: E501
        :type: LoadBalancer
        """

        self._lb_algorithm = lb_algorithm

    @property
    def servers(self):
        """Gets the servers of this VirtualServiceServerPool.  # noqa: E501


        :return: The servers of this VirtualServiceServerPool.  # noqa: E501
        :rtype: list[Host]
        """
        return self._servers

    @servers.setter
    def servers(self, servers):
        """Sets the servers of this VirtualServiceServerPool.


        :param servers: The servers of this VirtualServiceServerPool.  # noqa: E501
        :type: list[Host]
        """

        self._servers = servers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VirtualServiceServerPool, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VirtualServiceServerPool):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
