# coding: utf-8

"""
    CESv2 Remail Network API

    CESv2 Remail Network API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: cie-eng.network-hps-team@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.virtual_service_server_pool import VirtualServiceServerPool  # noqa: F401,E501


class VirtualServiceModifyRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'server_pool': 'VirtualServiceServerPool'
    }

    attribute_map = {
        'name': 'name',
        'server_pool': 'server_pool'
    }

    def __init__(self, name=None, server_pool=None):  # noqa: E501
        """VirtualServiceModifyRequest - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._server_pool = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if server_pool is not None:
            self.server_pool = server_pool

    @property
    def name(self):
        """Gets the name of this VirtualServiceModifyRequest.  # noqa: E501


        :return: The name of this VirtualServiceModifyRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VirtualServiceModifyRequest.


        :param name: The name of this VirtualServiceModifyRequest.  # noqa: E501
        :type: str
        """
        if name is not None and not re.search(r'^[a-z0-9]{6}-[0-9]{2}\\.iphmx\\.com$', name):  # noqa: E501
            raise ValueError(r"Invalid value for `name`, must be a follow pattern or equal to `/^[a-z0-9]{6}-[0-9]{2}\\.iphmx\\.com$/`")  # noqa: E501

        self._name = name

    @property
    def server_pool(self):
        """Gets the server_pool of this VirtualServiceModifyRequest.  # noqa: E501


        :return: The server_pool of this VirtualServiceModifyRequest.  # noqa: E501
        :rtype: VirtualServiceServerPool
        """
        return self._server_pool

    @server_pool.setter
    def server_pool(self, server_pool):
        """Sets the server_pool of this VirtualServiceModifyRequest.


        :param server_pool: The server_pool of this VirtualServiceModifyRequest.  # noqa: E501
        :type: VirtualServiceServerPool
        """

        self._server_pool = server_pool

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VirtualServiceModifyRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VirtualServiceModifyRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
